//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEventBookingSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int Booking_Id { get; set; }
        public string Booking_SeatNo { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Booking_Date { get; set; }
        public int Event_Id { get; set; }
        public int Booking_TicketCount { get; set; }
        public decimal Booking_TotalAmount { get; set; }
        public bool IsConfirmationSent { get; set; }
        public string Booking_Loc { get; set; }
    
        public virtual EventDetail EventDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
