//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEventBookingSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLocation
    {
        public int Location_Id { get; set; }
        public int Event_Id { get; set; }
        public decimal EventLocation_Price { get; set; }
        public System.DateTime EventLocation_DateAndTime { get; set; }
    
        public virtual EventDetail EventDetail { get; set; }
        public virtual Location Location { get; set; }
    }
}
